import type { ImageSourcePropType } from 'react-native';

// Gerado a partir de assets/charutos/cigar-mapping.json — não editar manualmente,
// regenerar caso novas imagens sejam adicionadas em assets/charutos/cigs-final/

export interface CigarCatalogEntry {
  key: string;
  name: string;
  brand: string;
  origin: string;
  image: ImageSourcePropType;
}

export const CIGAR_IMAGE_CATALOG: CigarCatalogEntry[] = [
  {
    key: 'Cohiba-Behike-52.png',
    name: 'Cohiba Behike 52',
    brand: 'Cohiba',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Cohiba-Behike-52.png'),
  },
  {
    key: 'Drew-Estate-Undercrown-Maduro.png',
    name: 'Drew Estate Undercrown Maduro',
    brand: 'Drew Estate (Undercrown)',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Drew-Estate-Undercrown-Maduro.png'),
  },
  {
    key: 'Sancho-Panza-Belicoso.png',
    name: 'Sancho Panza Belicoso',
    brand: 'Sancho Panza',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Sancho-Panza-Belicoso.png'),
  },
  {
    key: 'Partagas-Lusitania.png',
    name: 'Partagás Lusitania',
    brand: 'Partagás',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Partagas-Lusitania.png'),
  },
  {
    key: 'Fonseca-Cosacos.png',
    name: 'Fonseca Cosacos',
    brand: 'Fonseca',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Fonseca-Cosacos.png'),
  },
  {
    key: 'Crowned-Heads-Four-Kicudos.png',
    name: 'Crowned Heads Four Kicudos',
    brand: 'Crowned Heads',
    origin: 'Honduras/Nicaragua',
    image: require('../assets/charutos/cigs-final/Crowned-Heads-Four-Kicudos.png'),
  },
  {
    key: 'Trinidad-Reyes.png',
    name: 'Trinidad Reyes',
    brand: 'Trinidad',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Trinidad-Reyes.png'),
  },
  {
    key: 'Cohiba-Siglo-VI.png',
    name: 'Cohiba Siglo VI',
    brand: 'Cohiba',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Cohiba-Siglo-VI.png'),
  },
  {
    key: 'Punch-Punch.png',
    name: 'Punch Punch',
    brand: 'Punch',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Punch-Punch.png'),
  },
  {
    key: 'Jose-L-Piedra-Petit-Cazadores.png',
    name: 'José L. Piedra Petit Cazadores',
    brand: 'José L. Piedra',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Jose-L-Piedra-Petit-Cazadores.png'),
  },
  {
    key: 'Oliva-Serie-V-Melanio.png',
    name: 'Oliva Serie V Melanio',
    brand: 'Oliva',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Oliva-Serie-V-Melanio.png'),
  },
  {
    key: 'Oliva-Serie-G.png',
    name: 'Oliva Serie G',
    brand: 'Oliva',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Oliva-Serie-G.png'),
  },
  {
    key: 'Ashton-VSG.png',
    name: 'Ashton VSG',
    brand: 'Ashton',
    origin: 'Dominican Republic',
    image: require('../assets/charutos/cigs-final/Ashton-VSG.png'),
  },
  {
    key: 'Ashton-ESG.png',
    name: 'Ashton ESG',
    brand: 'Ashton',
    origin: 'Dominican Republic',
    image: require('../assets/charutos/cigs-final/Ashton-ESG.png'),
  },
  {
    key: 'My-Father-Flor-de-las-Antillas.png',
    name: 'My Father Flor de las Antillas',
    brand: 'My Father',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/My-Father-Flor-de-las-Antillas.png'),
  },
  {
    key: 'Ramon-Allones-Specially-Selected.png',
    name: 'Ramón Allones Specially Selected',
    brand: 'Ramón Allones',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Ramon-Allones-Specially-Selected.png'),
  },
  {
    key: 'Vegas-Robaina-Unicos.png',
    name: 'Vegas Robaina Unicos',
    brand: 'Vegas Robaina',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Vegas-Robaina-Unicos.png'),
  },
  {
    key: 'Plasencia-Alma-Fuerte.png',
    name: 'Plasencia Alma Fuerte',
    brand: 'Plasencia',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Plasencia-Alma-Fuerte.png'),
  },
  {
    key: 'Romeo-y-Julieta-Churchill.png',
    name: 'Romeo y Julieta Churchill',
    brand: 'Romeo y Julieta',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Romeo-y-Julieta-Churchill.png'),
  },
  {
    key: 'Plasencia-Alma-Fuerte-2.png',
    name: 'Plasencia Alma Fuerte',
    brand: 'Plasencia',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Plasencia-Alma-Fuerte-2.png'),
  },
  {
    key: 'El-Rey-del-Mundo-Choix-Supreme.png',
    name: 'El Rey del Mundo Choix Supreme',
    brand: 'El Rey del Mundo',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/El-Rey-del-Mundo-Choix-Supreme.png'),
  },
  {
    key: 'Illusione-Epernay.png',
    name: 'Illusione Epernay',
    brand: 'Illusione',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Illusione-Epernay.png'),
  },
  {
    key: 'Cohiba-Robusto.png',
    name: 'Cohiba Robusto',
    brand: 'Cohiba',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Cohiba-Robusto.png'),
  },
  {
    key: 'H-Upmann-Magnum-46.png',
    name: 'H. Upmann Magnum 46',
    brand: 'H. Upmann',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/H-Upmann-Magnum-46.png'),
  },
  {
    key: 'La-Gloria-Cubana-Medaille-DOr.png',
    name: 'La Gloria Cubana Medaille D\'Or',
    brand: 'La Gloria Cubana',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/La-Gloria-Cubana-Medaille-DOr.png'),
  },
  {
    key: 'Hoyo-de-Monterrey-Epicure-No2.png',
    name: 'Hoyo de Monterrey Epicure No. 2',
    brand: 'Hoyo de Monterrey',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Hoyo-de-Monterrey-Epicure-No2.png'),
  },
  {
    key: 'Hoyo-de-Monterrey-Epicure-No2-2.png',
    name: 'Hoyo de Monterrey Epicure No. 2',
    brand: 'Hoyo de Monterrey',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Hoyo-de-Monterrey-Epicure-No2-2.png'),
  },
  {
    key: 'Romeo-y-Julieta-Wide-Churchill.png',
    name: 'Romeo y Julieta Wide Churchill',
    brand: 'Romeo y Julieta',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Romeo-y-Julieta-Wide-Churchill.png'),
  },
  {
    key: 'San-Cristobal-El-Principe.png',
    name: 'San Cristóbal El Príncipe',
    brand: 'San Cristóbal',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/San-Cristobal-El-Principe.png'),
  },
  {
    key: 'Montecristo-No2.png',
    name: 'Montecristo No. 2',
    brand: 'Montecristo',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Montecristo-No2.png'),
  },
  {
    key: 'Montecristo-Especial.png',
    name: 'Montecristo Especial',
    brand: 'Montecristo',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Montecristo-Especial.png'),
  },
  {
    key: 'Bolivar-Royal-Corona.png',
    name: 'Bolívar Royal Corona',
    brand: 'Bolívar',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Bolivar-Royal-Corona.png'),
  },
  {
    key: 'Davidoff-Nicaragua-Box-Pressed.png',
    name: 'Davidoff Nicaragua Box-Pressed',
    brand: 'Davidoff',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Davidoff-Nicaragua-Box-Pressed.png'),
  },
  {
    key: 'Rocky-Patel-Decade.png',
    name: 'Rocky Patel Decade',
    brand: 'Rocky Patel',
    origin: 'Honduras',
    image: require('../assets/charutos/cigs-final/Rocky-Patel-Decade.png'),
  },
  {
    key: 'Perdomo-20th-Anniversary.png',
    name: 'Perdomo 20th Anniversary',
    brand: 'Perdomo',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Perdomo-20th-Anniversary.png'),
  },
  {
    key: 'Liga-Privada-No9.png',
    name: 'Liga Privada No. 9',
    brand: 'Drew Estate (Liga Privada)',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Liga-Privada-No9.png'),
  },
  {
    key: 'Davidoff-Winston-Churchill.png',
    name: 'Davidoff Winston Churchill',
    brand: 'Davidoff',
    origin: 'Dominican Republic',
    image: require('../assets/charutos/cigs-final/Davidoff-Winston-Churchill.png'),
  },
  {
    key: 'Partagas-Serie-D-No4.png',
    name: 'Partagás Serie D No. 4',
    brand: 'Partagás',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Partagas-Serie-D-No4.png'),
  },
  {
    key: 'Quai-dOrsay-Robusto.png',
    name: 'Quai d\'Orsay Robusto',
    brand: 'Quai d\'Orsay',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Quai-dOrsay-Robusto.png'),
  },
  {
    key: 'Trinidad-Vigia.png',
    name: 'Trinidad Vigia',
    brand: 'Trinidad',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Trinidad-Vigia.png'),
  },
  {
    key: 'Undercrown-Shade.png',
    name: 'Undercrown Shade',
    brand: 'Drew Estate (Undercrown)',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Undercrown-Shade.png'),
  },
  {
    key: 'Camacho-Triple-Maduro.png',
    name: 'Camacho Triple Maduro',
    brand: 'Camacho',
    origin: 'Honduras',
    image: require('../assets/charutos/cigs-final/Camacho-Triple-Maduro.png'),
  },
  {
    key: 'EP-Carrillo-Encore-Majestic.png',
    name: 'E.P. Carrillo Encore Majestic',
    brand: 'E.P. Carrillo',
    origin: 'Dominican Republic',
    image: require('../assets/charutos/cigs-final/EP-Carrillo-Encore-Majestic.png'),
  },
  {
    key: 'Alec-Bradley-Prensado.png',
    name: 'Alec Bradley Prensado',
    brand: 'Alec Bradley',
    origin: 'Honduras',
    image: require('../assets/charutos/cigs-final/Alec-Bradley-Prensado.png'),
  },
  {
    key: 'Foundation-Charter-Oak.png',
    name: 'Foundation Charter Oak',
    brand: 'Foundation',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Foundation-Charter-Oak.png'),
  },
  {
    key: 'Drew-Estate-Undercrown-Maduro-2.png',
    name: 'Drew Estate Undercrown Maduro',
    brand: 'Drew Estate (Undercrown)',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Drew-Estate-Undercrown-Maduro-2.png'),
  },
  {
    key: 'Diplomaticos-No2.png',
    name: 'Diplomáticos No. 2',
    brand: 'Diplomáticos',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Diplomaticos-No2.png'),
  },
  {
    key: 'Cohiba-Robusto-2.png',
    name: 'Cohiba Robusto',
    brand: 'Cohiba',
    origin: 'Cuba',
    image: require('../assets/charutos/cigs-final/Cohiba-Robusto-2.png'),
  },
  {
    key: 'Padron-Family-Reserve-45.png',
    name: 'Padrón Family Reserve 45',
    brand: 'Padrón',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Padron-Family-Reserve-45.png'),
  },
  {
    key: 'Arturo-Fuente-Opus-X.png',
    name: 'Arturo Fuente Opus X',
    brand: 'Arturo Fuente',
    origin: 'Dominican Republic',
    image: require('../assets/charutos/cigs-final/Arturo-Fuente-Opus-X.png'),
  },
  {
    key: 'Arturo-Fuente-Hemingway-Signature.png',
    name: 'Arturo Fuente Hemingway Signature',
    brand: 'Arturo Fuente',
    origin: 'Dominican Republic',
    image: require('../assets/charutos/cigs-final/Arturo-Fuente-Hemingway-Signature.png'),
  },
  {
    key: 'My-Father-Le-Bijou-1922.png',
    name: 'My Father Le Bijou 1922',
    brand: 'My Father',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/My-Father-Le-Bijou-1922.png'),
  },
  {
    key: 'Padron-1926-Serie-No9.png',
    name: 'Padrón 1926 Serie No. 9',
    brand: 'Padrón',
    origin: 'Nicaragua',
    image: require('../assets/charutos/cigs-final/Padron-1926-Serie-No9.png'),
  },
  {
    key: 'La-Aurora-1495.png',
    name: 'La Aurora 1495',
    brand: 'La Aurora',
    origin: 'Dominican Republic',
    image: require('../assets/charutos/cigs-final/La-Aurora-1495.png'),
  },
];

export const CIGAR_IMAGE_MAP: Record<string, ImageSourcePropType> = Object.fromEntries(
  CIGAR_IMAGE_CATALOG.map((entry) => [entry.key, entry.image]),
);
